### ISSUE TITLE
Example project does not work with 0.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by sduckett** [democracyworks/kehaar#15]
Kehaar is at 0.5.1-SNAPSHOT, so I should be able to install it locally and run the example like so:

```
(defproject kehaar-example "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [democracyworks/kehaar "0.5.1-SNAPSHOT"]]
  :main kehaar-example.core)
```

But when I run it, I am greeted with a stacktrace instead:

```
[~/src/kehaar/example] $ lein run
Feb 04, 2016 9:41:42 AM kehaar-example.core invoke
INFO: Starting up...
Feb 04, 2016 9:41:42 AM kehaar.rabbitmq invoke
INFO: RabbitMQ connected.
Exception in thread "main" java.io.IOException, compiling:(/private/var/folders/gx/5y8z31wd5kl1l4m7tss7718h0000gn/T/form-init8087786896758836557.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7239)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.io.IOException
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106)
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102)
        at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124)
        at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:834)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:258)
        at langohr.queue$declare.invoke(queue.clj:75)
        at kehaar.wire_up$external_service.invoke(wire_up.clj:84)
        at kehaar.wire_up$external_service.invoke(wire_up.clj:77)
        at kehaar_example.core$setup.invoke(core.clj:89)
        at kehaar_example.core$_main.doInvoke(core.clj:107)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at user$eval1035.invoke(form-init8087786896758836557.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        ... 11 more
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'calculate-fib' in vhost '/': received 'true' but current is 'false', class-id=50, method-id=10)
        at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:348)
        at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:221)
        at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
        ... 24 more
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'calculate-fib' in vhost '/': received 'true' but current is 'false', class-id=50, method-id=10)
        at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:478)
        at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:315)
        at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:144)
        at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:91)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:552)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tie-rack** [comment]
It looks like the channels the example project is trying to set up have already been declared with different attributes. Try deleting the channels in RabbitMQ and trying again.

**Comment by sduckett** [comment]
I couldn't find any channels or queues to delete, so I dug deeper. It looks to me like [commit 938eacc](https://github.com/democracyworks/kehaar/commit/938eacc1c8f85f63bccf55c6cbb127e2f3c58c3d) changed some defaults that weren't being specified in the example.
